### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/CashMoneyBlocks#15]
While this is a doozy of a lab, I didn't assign it this semester... it's too contrived and complicated for my taste. In the real world, subclassing or a protocol would *absolutely* be the way to do this (if the scenario arose at all), not a bunch of blocks. Also it tries to do a whole lot of stuff-- blocks as properties, test suite practice, blocks for externalizing logic, etc.

*Also*, it breaks a thing we've been telling them from early on -- that classes should be self-contained. Why should the tax logic live in a VC (or wherever), and be passed *in* to the CashRegister? It's not possible to make a useful CashRegister instance with the way this lab is set up. 

So... I think this should just be scrapped. If it lives on, it needs substantial work in the README and a thorough method/variable name audit.

**Comment by markedwardmurray** [comment]
I never attempted this lab as a student. I found it overwhelming. Only a few students from ios-004 actually tried it: Bert, Damon, maybe one or two more. Blocks were a major stumbling block (pun intended) for me, so more intermediate practice with blocks i think would be beneficial to the experience.
